name: Upload PDF
on:
  release:
    types: [published]
 
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: main.pdf